### ISSUE TITLE
GitHub Actions을 이용한 확장 플러그인 자동 배포의 필요성

### ISSUE THREAD

**Issue by nbsp1221** [kw-service/klas-helper-extension#22]
현재는 @mirusu400 님이 수동으로 배포하고 있는 것으로 알고 있습니다. 지금 상황에서는 배포를 @mirusu400 님밖에 할 수 없고 코드가 변경될 때마다 매번 수동으로 배포를 하는 것도 부담으로 이어질 것 같아서 GitHub Actions를 이용해 CD를 셋업 하는 것이 좋을 것 같습니다.

- https://github.com/marketplace/actions/chrome-extension-upload-action
- https://jam.dev/blog/automating-chrome-extension-publishing
- https://hoonti06.gitlab.io/wiki/deploy-chrome-extension-using-github-actions

조금 찾아보니까 기술적으로는 충분히 가능할 것으로 보입니다. 다만 이를 위해서는 @mirusu400 님이 접근 권한이 있는 토큰을 발급받아 배포에 필요한 값들을 GitHub Secrets에 먼저 등록해 주셔야 할 것 같습니다.

CD 셋업은 릴리즈를 새로 만들 때마다 프로그램이 배포되도록 작업해 보겠습니다.

다른 의견 있다면 댓글 남겨주세요!

아, 그리고 추가적으로 이슈나 PR, 커밋 등 저희 레포를 트래킹하거나 실시간으로 서로 소통할 수 있는 수단이 있으면 좋을 것 같은데 KLAS Helper 디스코드를 하나 만드는 건 어떨까요?

**Comment by mirusu400** [comment]
Google에서도 토큰을 제공해 주는군요 😅 처음알았네요. 글을 읽어보니 충분히 자동 릴리즈는 가능해 보입니다.

다만 걱정되는 부분이 몇가지 있는데,

* 단순히 새로운 릴리즈를 크롬 확장 대시보드에 업로드하면 바로 반영되는것이 아닌 관리자(구글측)의 승인이 있어야 반영된다는 점
* 제가 수동으로 새 릴리즈 시 KLAS Helper 확장프로그램 대시보드에 Description으로 Changelog를 작성하고 있다는 점
* 파이어폭스는 따로 별도의 확장 프로그램 스토어가 있다는 점
* 파이어폭스 스토어는 코드가 압축되어있을 경우 원본을 같이 올려야 된다는 점

등이 있습니다.
아마 첫번째 건은 큰 문제가 없을 것 같고, 두번째 건 또한 레포에 작성후 CI/CD로 해결이 가능할 것 같지만, 3,4번째 건은 확인이 필요해 보입니다.

사실 파이어폭스 지원은 2버전 들어와서 Manifest v3 이후 제대로 확인을 안했고, 스토어 업로드도 안하고 있는 상태에서 만약 추가 지원을 할 예정이라면 다시한번 점검이 필요합니다.

시크릿 값 추가는 시간 나는대로 진행하도록 하겠습니다

그 외에 디코 만드는건 좋아 보입니다 😄  요즘 대형 레포들 전부 Github 훅 걸어서 디스코드로 관리하더라고요

**Comment by mirusu400** [comment]
https://github.com/fregante/chrome-webstore-upload/blob/main/How%20to%20generate%20Google%20API%20keys.md

위 글 확인후 해당 Repo Secret에 Client ID, Client Secret, Refresh Token 갱신해놨습니다.

**Comment by nbsp1221** [comment]
확인했습니다. 감사합니다

**Comment by nbsp1221** [comment]
이 이슈는 현재 정상적으로 동작하는 것 같으니 닫도록 하겠습니다.
