### ISSUE TITLE
졸업생 성적 조회 페이지 적용

### ISSUE THREAD

**Issue by kseenyoung** [kw-service/klas-helper-extension#31]
졸업생은 '졸업생 성적 조회'탭만 활성화 되는데, Helper가 적용 안 돼서 슬픕니다ㅜㅜ 재학생 '성적 조회'화면과 동일하게 적용해주실 수 있으신가요?

**Comment by mirusu400** [comment]
안녕하세요

현재 이 레포를 유지하는 개발자분들 중 졸업생이 안계셔서 해당 URL을 잘 몰라 적용이 힘듭니다..

프로젝트 기여에 관심이 있으시다면, [src/routes/index.js](https://github.com/kw-service/klas-helper-extension/blob/main/src/routes/index.js) 파일을 간단하게 수정하는 것 만으로 구현이 가능해보입니다

확인해보시고 PR주시면 반영하겠습니다~
